server:
  port: 5000

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    reactor.netty: WARN

spring:
  aop:
    proxy-target-class: true
  webflux:
    base-path: /

app:
  service:
    parallelism: 4
    detail-timeout-ms: 2000

  external:
    base-url: ${EXTERNAL_BASE_URL:http://localhost:3001}